ERMS0831/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import depart, user, pretty, admin, account

urlpatterns = [

    # 部门管理
    # path('admin/', admin.site.urls),
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    # 含有正则表达的
    # http://127.0.0.1:8000/depart/1/edit/
    path('depart/<int:nid>/edit/', depart.depart_edit),

    # 用户管理
    path("user/list/", user.user_list),
    path("user/add/", user.user_add),
    path('user/<int:nid>/edit/', user.user_edit),
    # path('user/delete/', views.user_delete),
    path('user/<int:nid>/delete/', user.user_delete),

    # 号码管理
    path("pretty/list/", pretty.pretty_list),
    path("pretty/add/", pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    # 管理员
    path("admin/list/", admin.admin_list),
    path("admin/add/", admin.admin_add),
    path("admin/<int:nid>/edit/", admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code)
]

app01/models.py
from django.db import models


# Create your models here.
class Admin(models.Model):
    # 管理员
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)


class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class User_info(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name="姓名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")

    # 无约束
    # depart_id = models.BigIntegerField(verbose_name="部门ID")

    # 有约束 django 写 depart 生成  depart_id
    # 有约束                    to 与那张表关联    to_field 表中的一列关联        级联删除
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
    # 有约束                    to 与那张表关联    to_field 表中的一列关联        置空
    # depart = models.ForeignKey(id="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

    # django 代码中约束
    gender_choices = ((1, "男"), (2, "女"),)
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    """ 手机号表 """
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = ((1, "1级"), (2, "2级"), (3, "3级"), (4, "4级"),)
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = ((1, "已占用"), (2, "未占用"))
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)

app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models

from app01.utils.form import LoginForm
from app01.utils.code import check_code

from io import BytesIO


def login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功 获取到用户信息 form.cleaned_data
        # {'username': '123', 'password': 'cfdaf9256fd1262ab42bf8a3a573f338', 'code':'xxx'}
        # 需要校验
        # print(form.cleaned_data)

        user_input_code = form.cleaned_data.pop("code")
        code = request.session.get("image_code", "")
        if code == "":
            form.add_error("code", "验证码已超时")
            return render(request, 'login.html', {"form": form})

        if user_input_code.upper() != code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {"form": form})

        # 去数据库校验用户和密码是否正确 获取用户对象
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:  # 如果 没查到 这位 None
            form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {"form": form})

        # session cookie
        # 网站生成随机字符串 存到 cookie 中 浏览器 和服务器 各保存一份， info中 保存对应的session ，序列化到 django-session 表中
        # 检查-网络-全部-list-cookie sessionid 的随机字符串   django-session 表中
        # 不同浏览器 cookie session 不同
        request.session["info"] = {"id": admin_object.id, "username": admin_object.username}
        # session 可以保存一个月
        request.session.set_expiry(60 * 60 * 24 * 30)
        return redirect('/admin/list/')

    return render(request, 'login.html', {"form": form})


def logout(request):
    request.session.clear()
    return redirect("/login/")


def image_code(request):
    img, code_string = check_code()
    # print(code_string)

    # 写入到session中 （以便后续读取验证码 再进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s的超时
    request.session.set_expiry(60)

    stream = BytesIO()  # 创建一个对象
    img.save(stream, 'png')  # 图片内容 写入内存

    return HttpResponse(stream.getvalue())

app01/views/admin.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminModelForm, AdminEditModelForm,AdminResetModelForm


def admin_list(request):
    # 管理员

    # 构造搜索条件
    data_dict = {}
    search_data = request.GET.get('q')
    if search_data:
        data_dict["username__contains"] = search_data
    else:
        search_data = ""

    # 去数据库搜索
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_object = Pagination(request, queryset)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
        "search_data": search_data
    }
    return render(request, "admin_list.html", context)


def admin_add(request):
    # 添加管理员
    title = "新建管理员"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change.html', {"form": form, "title": title})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        # {'username': '刘琪', 'password': '123123', 'confirm_password': '123123'}
        form.save()
        return redirect("/admin/list/")
    return render(request, 'change.html', {"form": form, "title": title})


def admin_edit(request, nid):
    # 编辑管理员

    # 判断 url 中的 nid 是否在数据库中（可能多人操作时 被删除） 增加判断
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "数据不存在"})

    title = "编辑管理员"
    if request.method == "GET":
        # form = AdminModelForm(instance=row_object) # 可以复用admin add的form
        form = AdminEditModelForm(instance=row_object)  # instance row object 实现输入时，呈现默认数据
        return render(request, 'change.html', {"form": form, "title": title})
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    # 在Django中使用modelform保存数据时，通常需要传递一个instance参数，以指定要保存的数据库记录。
    # instance参数用于表示要更新或修改的现有记录，如果要创建新记录，则可以不传递instance参数。
    # 如果您传递了instance参数，modelform将根据该instance对象的主键来更新相应的数据库记录。
    # 如果不传递instance参数，modelform将创建一个新的数据库记录。
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'change.html', {"form": form, "title": title})


def admin_delete(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "数据不存在"})
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list/")


def admin_reset(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "数据不存在"})
    title = "重置密码 - {}".format(row_object.username)

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, 'change.html', {"form": form, "title": title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'change.html', {"form": form, "title": title})

app01/views/depart.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import UserModleForm, PrettyNumModleForm, PrettyNumEidtModleForm


def depart_list(request):
    """部门列表"""
    # 去数据库中获得所有部门表
    # [对象，对象]
    queryset = models.Department.objects.all()

    return render(request, 'depart_list.html', {'queryset': queryset})


def depart_add(request):
    """添加部门"""
    if request.method == "GET":
        return render(request, 'depart_add.html')

    title = request.POST.get("title")
    models.Department.objects.create(title=title)

    return redirect("/depart/list/")


def depart_delete(request):
    """删除部门"""
    # http://127.0.0.1:8000/depart/delete/?nid=1
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")


def depart_edit(request, nid):
    """修改部门"""
    # http://127.0.0.1:8000/depart/1/edit/
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"row_object": row_object})
    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")

app01/views/pretty.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import UserModleForm, PrettyNumModleForm, PrettyNumEidtModleForm


def pretty_list(request):
    # 随机创建500条数据
    # for i in range(10):
    #     for j in range(10):
    #         for k in range(5):
    #             mobile = '18188886' + str(i) + str(j) + str(k)
    #             models.PrettyNum.objects.create(mobile=mobile, price=10, level=1, status=1)

    # 相当于 select * from 表 order by level desc

    # queryset = models.PrettyNum.objects.all().order_by("-level")
    # queryset = models.PrettyNum.objects.all()

    # 搜索框
    data_dict = {}
    search_data = request.GET.get('q')
    if search_data:
        data_dict["mobile__contains"] = search_data
    else:
        search_data = ""
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-level")

    page_object = Pagination(request, queryset, page_size=10)

    context = {
        "search_data": search_data,
        "queryset": page_object.page_queryset,  # 分完也的数据
        "page_string": page_object.html(),  # 页码
    }
    return render(request, "pretty_list.html", context)


############################## 靓号提交 先建form类

def pretty_add(request):
    title = "新建靓号"
    if request.method == "GET":
        form = PrettyNumModleForm()
        return render(request, "change.html", {"form": form, "title":title})

    form = PrettyNumModleForm(data=request.POST)

    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')

    return render(request, "change.html", {"form": form, "title":title})


# 编辑 form 类


def pretty_edit(request, nid):
    row_object = models.PrettyNum.objects.filter(id=nid).first()

    if request.method == "GET":
        form = PrettyNumEidtModleForm(instance=row_object)
        return render(request, "pretty_edit.html", {"form": form})

    form = PrettyNumEidtModleForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')
    return render(request, "pretty_edit.html", {"form": form})


def pretty_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect("/pretty/list/")

app01/views/user.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import UserModleForm, PrettyNumModleForm, PrettyNumEidtModleForm


def user_list(request):
    queryset = models.User_info.objects.all()

    page_object = Pagination(request, queryset, page_size=2)
    context = {
        "queryset": page_object.page_queryset,  # 分完页之后的数据
        "page_string": page_object.html()  # 页面中的页码
    }

    return render(request, "user_list.html", context)


# ##################################  modleForm 实现   ##################################


def user_add(request):
    # if request.method == "GET":
    #     context = {
    #         "gender_choices": models.User_info.gender_choices,
    #         "depart_list": models.Department.objects.all(),
    #     }
    #     return render(request, "user_add.html", context)

    # 获取数据(原始方法)
    # user = request.POST.get("name")......
    # models.User_info.objects.create(name = user)

    if request.method == "GET":
        form = UserModleForm()
        return render(request, "user_add.html", {"form": form})

    # POST 提交数据校验
    form = UserModleForm(data=request.POST)
    # 添加校验
    if form.is_valid():
        # 存储到表里面
        form.save()
        return redirect("/user/list")

    return render(request, "user_add.html", {"form": form})


def user_edit(request, nid):
    """修改部门"""
    # http://127.0.0.1:8000/user/1/edit/
    row_object = models.User_info.objects.filter(id=nid).first()

    if request.method == "GET":
        form = UserModleForm(instance=row_object)
        return render(request, "user_edit.html", {"form": form})

    form = UserModleForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存 用户输入的所有数据， 如果想保存用户输入以外增加一点值
        # form.instance.password（字段名） = 值

        form.save()  # 添加数据
        return redirect("/user/list")
    return render(request, 'user_edit.html', {"form": form})


def user_delete(request, nid):
    """删除部门"""
    # http://127.0.0.1:8000/depart/delete/?nid=1
    # nid = request.GET.get('nid')
    models.User_info.objects.filter(id=nid).delete()
    return redirect("/user/list/")

app01/templates/admin_list.html
{% extends "layout.html" %}

{% block content %}
    <div style="margin-bottom: 20px" class=clearfix>
        <a class="btn btn-success" href="/admin/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建管理员
        </a>

        <div style="float: right ; width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="关键字"
                           value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            管理员列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>用户名</th>
                <th>密码</th>
                <th>重置密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.username }}</td>
                    <td>***********</td>
                    <td>
                        <a href="/admin/{{ obj.id }}/reset/">重置</a>
                    </td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编 辑</a>
                        {#                        <a class="btn btn-danger btn-xs" href="/user/delete/?nid={{ obj.id }}">删 除</a>#}
                        <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">删 除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class=clearfix>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

{% endblock %}

app01/templates/change.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>

        <div class="panel-body">
            <form method="post" novalidate>

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <lable>{{ field.label }}</lable>
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                        {#                    <input type="text" class="form-control" placeholder="姓名">#}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">提 交</button>

            </form>
        </div>


    </div>

{% endblock %}

app01/templates/depart_add.html
{% extends "layout.html" %}

{% block content %}


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">新建部门</h3>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" placeholder="部门名称" name="title"/>
            </div>
            <button type="submit" class="btn btn-primary">提 交</button>
        </form>
    </div>
</div>

{% endblock %}

app01/templates/depart_edit.html
{% extends "layout.html" %}

{% block content %}


    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">新建部门</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="部门名称" name="title" value="{{ row_object.title }}"/>
                </div>
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>


{% endblock%}

app01/templates/depart_list.html
{% extends "layout.html" %}

{% block content %}

    <div style="margin-bottom: 20px">
        <a class="btn btn-success" href="/depart/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建部门
        </a>
    </div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            部门列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>部门名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}

                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编 辑</a>
                        <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ obj.id }}">删 除</a>
                    </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color :red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color :red;">{{ form.password.errors.0 }}</span>
        </div>

        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color :red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/">
                </div>
            </div>
        </div>

        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

app01/templates/pretty_add.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">新建靓号</h3>
        </div>

        <div class="panel-body">
            <form method="post" novalidate>

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <lable>{{ field.label }}</lable>
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                        {#                    <input type="text" class="form-control" placeholder="姓名">#}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">提 交</button>

            </form>
        </div>


    </div>

{% endblock %}

app01/templates/pretty_edit.html
{% extends "layout.html" %}

{% block content %}


    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">编辑号码</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                <form method="post" novalidate>

                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <lable>{{ field.label }}</lable>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                            {#                    <input type="text" class="form-control" placeholder="姓名">#}
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
        </div>
    </div>


{% endblock %}

app01/templates/pretty_list.html
{% extends "layout.html" %}

{% block content %}
    <div style="margin-bottom: 20px" class=clearfix>
        <a class="btn btn-success" href="/pretty/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建号码
        </a>

        <div style="float: right ; width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search for..."
                           value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            号码列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>手机号</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.mobile }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/pretty/{{ obj.id }}/edit">编 辑</a>
                        {#                        <a class="btn btn-danger btn-xs" href="/user/delete/?nid={{ obj.id }}">删 除</a>#}
                        <a class="btn btn-danger btn-xs" href="/pretty/{{ obj.id }}/delete">删 除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class=clearfix>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}

    <div class="panel panel-default">

        <div class="panel-heading">
            <h3 class="panel-title">新建用户</h3>
        </div>

        <div class="panel-body">
            <form method="post" novalidate>

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <lable>{{ field.label }}</lable>
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                        {#                    <input type="text" class="form-control" placeholder="姓名">#}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary">提 交</button>

            </form>
        </div>


    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>

    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });
        })

    </script>
{% endblock %}

app01/templates/user_list.html
{% extends "layout.html" %}

{% block content %}

    <div style="margin-bottom: 20px">
        <a class="btn btn-success" href="/user/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建用户
        </a>
    </div>

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            用户列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>name</th>
                <th>age</th>
                <th>gender</th>
                <th>password</th>
                <th>account</th>
                <th>create time</th>
                <th>depart</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.create_time }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编 辑</a>
                        {#                        <a class="btn btn-danger btn-xs" href="/user/delete/?nid={{ obj.id }}">删 除</a>#}
                        <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删 除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

{% endblock %}